import ScrollToTopButton from "@/components/ScrollToTopButton";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata = {
  title: "Display-Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={montserrat.className}
        suppressHydrationWarning
      >
        <ReactQueryProvider>
          {children}
          <ScrollToTopButton />
          <Toaster
            position="bottom-right"
            reverseOrder={false}
          />
        </ReactQueryProvider>
      </body>
    </html>
  );
}